# Generated by Django 5.1.1 on 2025-04-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coaches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coaches',
        ),
    ]
