# Generated by Django 5.1.1 on 2025-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=64, unique=True, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
    ]
