# Generated by Django 5.1.1 on 2025-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='support',
        ),
    ]
