# Generated by Django 5.1.1 on 2025-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='mail',
            field=models.TextField(max_length=64, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения  '),
        ),
    ]
