# Generated by Django 5.1.1 on 2025-04-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_support_mail_alter_support_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='support',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
