# Generated by Django 5.1.1 on 2025-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='article',
            new_name='product',
        ),
    ]
