# Generated by Django 5.1.1 on 2025-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_rename_article_reviews_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64, verbose_name='ФИО')),
                ('classification', models.TextField(max_length=64, verbose_name='Классификация')),
                ('text', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Изображение')),
            ],
        ),
    ]
